services:
  catalogdb:
    image: postgres:12-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
